### PR TITLE
Fix a null safety error in the [SecureGate]

### PR DESCRIPTION
**Pull request by lubritto**
error: type List<Widget?> is not a subtype of type List<Widget> in type cast.

```
<Widget?>[
  widget.child,
  if (_gateVisibility.value != 0)
    Positioned.fill(
      child: BackdropFilter(
        filter: ImageFilter.blur(
            sigmaX: widget.blurr * _gateVisibility.value,
            sigmaY: widget.blurr * _gateVisibility.value),
        child: Container(
          decoration: BoxDecoration(
              color: Colors.grey.shade200
                  .withOpacity(widget.opacity * _gateVisibility.value)),
        ),
      ),
    ),
  if (_lock && widget.lockedBuilder != null)
    widget.lockedBuilder!(context, _secureApplicationController),
] as List<Widget>,
```

### CODE REVIEW

**Comment by tsuruobiz** [comment]
Same problem. Thanks for your fix commit https://github.com/neckaros/secure_application/pull/17/commits/7db360120962ac440910a140b5fcb5d6ae475352

**Comment by tsuruobiz** [comment]
Same problem. I'm waiting that the PR is merged as soon as possible.

**Comment by abhinandval** [comment]
#18 

had same issue I've made the widget parameter to secure gate non-null. since the widget is passed to add in a Stack I think it can never be a null-able widget.

**Comment by tsuruobiz** [comment]
Any update?

**Comment by neckaros** [comment]
Hello, i merged the other pull request that fix also this issue. Thanks a lot @lubritto !

**Pull request closed without merging**
