### PR TITLE
[WIP] Add the possibility of changing the shield view and blur alpha

### PR DESCRIPTION
**Pull request by lubritto**
Add the possibility of changing the shield view and blur alpha on the native code, to have custom shield views.

plugin_feature

### CODE REVIEW

**Comment by neckaros** [comment]
Hello, that’s a cool feature. Is it still in WIP?

**Comment by lubritto** [comment]
Yess, I had to stop for a while and focus on other issues, but will be able to continue the work this week

**Comment by adnankhan74444** [comment]
This is really a cool feature.

**Comment by lubritto** [comment]
Unfortunately Android doesn't support changing the background, for now closing this PR

**Pull request closed without merging**
